spring.application.name=api-gateway
server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinition = INFO
logging.level.org.springframework.cloud.gateway= TRACE

## product service
## use lb to ude the load balancing of the client side
spring.cloud.gateway.server.webmvc.routes[0].id=product-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://product-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/products/**

# order service routes
spring.cloud.gateway.server.webmvc.routes[1].id=order-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://order-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/order/**

# discovery server route
spring.cloud.gateway.server.webmvc.routes[2].id=discovery-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8761
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/eureka/web/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=SetPath=/

## Discovery service static resources route like css
spring.cloud.gateway.server.webmvc.routes[3].id=discovery-service-static
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8761
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/eureka/**
