spring.application.name=product-service
server.port=8083
spring.data.mongodb.uri=mongodb://admin:password123@localhost:27017/product-service?authSource=admin


## where we are going to find the eureka server
# URL	                        Purpose
#http://localhost:8761	        Eureka Dashboard (UI)
#http://localhost:8761/eureka	REST endpoint used by Eureka clients
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
