spring.application.name=product-service
server.port=0
spring.data.mongodb.uri=mongodb://localhost:27017/product-service



## where we are going to find the eureka server
# URL	                        Purpose
#http://localhost:8761	        Eureka Dashboard (UI)
#http://localhost:8761/eureka	REST endpoint used by Eureka clients
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

